### ISSUE TITLE
Create `"spread"` version of relative / ordinal modifiers

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1514]
Eg `"take spread three tokens"`, `"take spread first three tokens"`, etc, which instead of creating a range between scopes, yields each scope in the range.  It's just shorthand for `"every <scope> <modifier>"` but is common enough to be useful.

Might consider just using the word `"every"`, eg `"take every three tokens"`?  Or `"split"`?

Could be extra boolean field on these scopes in the Cursorless api

Could steal code from `"instance"`, and potentially would allow us to have `"instance"` reuse more of our existing code, as one of the primary differences in the `"instance"` pseudo-scope is that it defaults to a `"spread"` scope

**Comment by josharian** [comment]
Not quite the same, but I keep wanting to say `swap two args air` or `swap two paints drum`. If swap swapped two targets, then maybe this could be `swap spread two args air`. Currently it is `swap paint drum with its next paint`. (Alternatively, this could be another use case for https://github.com/cursorless-dev/cursorless/issues/492.)

**Comment by pokey** [comment]
Yeah was thinking we should maybe support a single-target version of swap. Then you could say "swap air and bat" or "swap spread two args air"

**Comment by bra1nDump** [comment]
"change three instances trap"

When writing prose or strings within my applications, I often want to refer to fixed number of occurrences after the first instance. For example I made a typo, then copied it over, and now I need to replace both occurrences, but I don't want to risk using every or having to think about scoping those down, I literally see two occurrences and I want only them to be replaced.

```typescript
if (...) {
    throw new Error('Tell was deleted')
} else if (...) {
    throw new Error('Tell index is out of bounds')
} else {
    console.log('Tell is good to go')
}
```

Currently I would use:
- change trap and each and look
- from function change every instance trap
- change three instances trap

**Comment by pokey** [comment]
Not totally following, but maybe you're looking for "next three instances trap"?

**Comment by bra1nDump** [comment]
'next two instances' was exactly what I was looking for!

Also like the suggested spread, I'm in favor of reusing every.

For this string (| is the cursor):
`aaa |  bbb ccc ddd eee`

`bbb, ccc, ddd` can be multi-selected with
- "take every token past drum" (also a new command I discovered)
- "take every token three tokens" - this already works, and seems pretty close to the proposal
- "take every three tokens" - this is the proposal

I like reusing the word every for this because it already does what we want, although with some redundancy. Maybe this feature can even be implemented in terms of the old modifier, by inferring the scope from the target. For example: "take every three keys" would be equivalent to "take every key three keys".
