### ISSUE TITLE
""Please first focus an application" when vscode is focused.  "cursorless reference" does not work.  "and honey underscore lucy" repeats.

### ISSUE THREAD

**Issue by davehorner** [cursorless-dev/cursorless#1951]
hey just giving it a spin.

"and honey underscore lucy" keeps repeating on my headset.

if I say "cursorless help" chrome opens the documentation, great.

if I say "cursorless reference" it tells me "Please first focus an application that supports cursorless, eg say "focus code""
I am in code. I see the color'd dots.  i see cursorless in the status bar.
there are no error lines in Talon Log Viewer.

I do have viumium installed, I'm wondering if I need to be concerned with that?

**Comment by davehorner** [comment]
https://github.com/talonhub/community
once I put the community in the user folder things started to work!

**Comment by pokey** [comment]
Yes, you won't get far without the community commands ☺️. In case helpful, [here's](https://www.cursorless.org/docs/user/installation/) the installation guide

I wonder if we should try to detect this situation and show an error message. Eg look for an action we require and throw an error on load if we can't find it

In that vein, I bet we could also detect if user clones cursorless monorepo instead of cursorless-talon. We could just drop a simple Python file at the root that shows an error message. WDYT @AndreasArvidsson ?

**Comment by AndreasArvidsson** [comment]
Sounds workable, but I'm wondering if it could be annoying when you're actually developing cursorless?

**Comment by pokey** [comment]
Why would you get that error when you're developing cursorless? The python file would be at the root of the monorepo, which should never be copied / symlinked into your Talon user dir, even during development, unless I'm missing something?

**Comment by pokey** [comment]
@AndreasArvidsson let's move the discussion to #1953
