### ISSUE TITLE
"Take inside" doesn't work in C++ with #pragma line

### ISSUE THREAD

**Issue by patrickreece2** [cursorless-dev/cursorless#2316]
In C++, if I use "take inside" to try and take the text "-Wdeprecated-declarations", it doesn't work.

```c
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```

**Comment by AndreasArvidsson** [comment]
In the c++ parse tree everything after pragma is just one single opaque node. . We don't have access to if this is a string style argument, where the quotes are or anything like what we have with normal strings. We have to switch to a more text based approach instead of relying as much on the parse tree as we are doing today. This isn't really a bug we can fix with the c++ implementation; we have to basically rewrite our surrounding pairs win a new paradigm. Lucky for us I'm already working on exactly this :D

https://github.com/cursorless-dev/cursorless/pull/2457
