### ISSUE TITLE
neovim: `Neovim: Test` launch command doesn't auto attach to neovim node process on Linux

### ISSUE THREAD

**Issue by fidgetingbits** [cursorless-dev/cursorless#2446]
Currently the documentation for running and testing the extension states:

```markdown
## Running / testing extension locally

In order to test out your local version of the extension or to run unit tests locally, you need to run the extension in
debug mode. To do so you need to run the `workbench.action.debug.selectandstart` (aka `Debug: Select and Start Debugging`) command in VSCode and then select either "Neovim: Run" or "Neovim: Test".

The debug logs are written in `C:\path\to\cursorless\packages\cursorless-neovim\out\nvim_node.log`.
```

On Linux when I run "Neovim: Test" it spawns a shell with the new neovim instance and then just hangs. This in turn leads bug #2445 . The solution is to manually tell VSCode to attach to the node process, at which point the tests will actually be able to run, and `nvim_node.log` is populated.

The `launch.json` file contains:

```
    {
      "name": "Neovim: Test",
      "request": "attach",
      "continueOnAttach": true,
      "skipFiles": ["<node_internals>/**"],
      "preLaunchTask": "Neovim: Build extension and tests",
      "type": "node"
    },
```

but it seems like this `attach` doesn't actually auto attach. The `debug-neovim.sh` script explicitly sets `export NVIM_NODE_HOST_DEBUG="1"`, so it is waiting for something to attach.

**Comment by saidelike** [comment]
This seems like a weird vscode setting problem or vscode bug to me. 

It might be worth playing with the parameters in the `launch.json` file you mention above (such as removing `continueOnAttach`, checking if some of them are not supported on Linux.

FWIW it will only attach if all the other tasks are successfully executed so it could take a few dozen seconds to 1 minute before it attaches.

Another thing worth checking is that the `node.exe` process spawned by `nvim.exe` actually has the `--inspect-brk` flag which is required in order to attach, but seems you said you manage to attach manually, it should be the case.

**Comment by saidelike** [comment]
Actually, since you start `nvim` differently on Linux by spawning a new terminal, it might be worth double checking all environment variables are set correctly in your spanwed `nvim` and hence `node` subprocess.

https://github.com/saidelike/cursorless/blob/1cdf49ee6480e54b2acdb9e34275e458fa63631a/packages/cursorless-neovim/scripts/debug-neovim.sh#L7

```bash
export CURSORLESS_REPO_ROOT="${workspaceFolder}"
export NVIM_NODE_HOST_DEBUG="1"
export NVIM_NODE_LOG_FILE="${workspaceFolder}/packages/cursorless-neovim/out/nvim_node.log"
export NVIM_NODE_LOG_LEVEL="info"
export CURSORLESS_MODE="${cursorless_mode}"
```

**Comment by fidgetingbits** [comment]
I'm not sure what changed exactly, but after rebasing the linux test task PR to the latest nvim-talon branch and re-testing it's auto attaching within a couple seconds... so I will close this unless I run into it again eventually
