### ISSUE TITLE
Generator functions in javascript don't work

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#312]
We can't select a generator function when we say "take funk"

**Comment by AndrewDant** [comment]
Can you give an example of something that isn't working? Saying "take funk" works on the generator function below:
`function* generator(i) {
    yield i;
    yield i + 10;
}`

**Comment by nathanheffley** [comment]
@AndrewDant it should work in JavaScript and PHP (I fixed it in both of those languages). I don't know if there are generator functions in other languages that aren't supported. This would be an easy win if you can find languages where it's not supported, otherwise this ticket may be able to just be closed.

**Comment by pokey** [comment]
This was fixed by #600
