### ISSUE TITLE
Allow disabling colored shapes

### ISSUE THREAD

**Issue by AndrewDant** [cursorless-dev/cursorless#603]
Currently if colors and shapes are both enabled some of the shape hats will also have colors. This allows additional tokens to have hats but results in longer selectors (i.e. "take blue bolt bat"). Additionally it is harder to determine the color of some shapes than others. For example the bolt shape has far less area than the default circle. Therefore I suggest adding a setting to disable colored shapes so that when colors and shapes are both enabled only one or the other will be used at time.

**Comment by pokey** [comment]
The approach  Iwas thinking was to add a `maxPenalty` setting.

By default, colours and shapes each have a penalty of 1, and any style combination adds penalties of constituents.  So, for example `blue` has a penalty of 1, and `fox` has a penalty of 1.  Then we have the following penalties for the following style combinations:

- "air" has a penalty of 0
- "blue air" has a penalty of 1
- "fox air" has a penalty of 1
- "blue fox air" has a penalty of 2

Notice that these penalties correspond to the number of syllables need to be said (ignoring "air", which must always be said)

If you don't want coloured shapes, you can set your `maxPenalty` to something between 1 and 2.  This approach provides more flexibility, because you could use it to disable some specific shape / colour combinations by giving some colours / shapes penalties slightly higher than 1

Does this approach make sense to you?

**Comment by AndrewDant** [comment]
One concern I have with this approach is that it ties extra logic/meaning to values that already have their own meaning. So if I'm changing the penalty of certain colors/shapes I have to also consider how that interacts with the penalties of my shapes as compared to my max penalty. For example if my current penalties are:

- red: 1
- blue: 1
- yellow: 2
- fox: 1
- bolt: 2

and I wish to have all colors or shapes, but no colored shapes, while keeping the same relative penalties (yellow has twice the penalty of other colors, bolt twice the penalty of fox), how would I achieve that? I'm not sure of the significance of the relative magnitude of values of the penalties (i.e. setting yellow to 2 vs 3, or 2 vs 1.1) so this may be a non issue.

**Comment by pokey** [comment]
It is fair that we might be mixing concerns a bit here.  I was mainly hoping to avoid a cross-product of settings to be able to disable any specific pair.  So if you really just want to disable all coloured shapes, without being able to control specific pairs, then one setting to disable coloured shapes is probably fine

Fwiw in your case if we went with max penalty, I'd probably set your 2's to 1.5's, and then set a max penalty of 2.  For ranking, it just adds the penalties of the constituent words (eg your "blue bolt" would become 3), then just sorts, so all that matters is relative rank

**Comment by AndrewDant** [comment]
It sounds like one setting to disable colored shapes would do the job for what I want (assuming the default circle doesn't count as a 'shape'). That said if the only thing that matters is relative rank then I'm not opposed to your idea either. I'd be interested in trying to make this update myself but I would need some help. Where in the code does it determine which shape and color to use for a certain token?

**Comment by pokey** [comment]
This is the area you'll want to look at https://github.com/cursorless-dev/cursorless-vscode/blob/16dc10e28096edb0ede3faf7962d3f48a7e6e85c/src/core/Decorations.ts#L202-L220
