### ISSUE TITLE
When you say "chuck line target1 between target2" a single empty line sticks around. 

### ISSUE THREAD

**Issue by RonWalker22** [cursorless-dev/cursorless#625]
All lines between target1 and target2 should be removed. 

In my gif example below “ace” is `}`. 

![chuck between](https://user-images.githubusercontent.com/18250094/160606644-10452d81-2d81-418f-b814-594c96e48eb2.gif)

**Comment by Will-Sommers** [comment]
Heyo, taking a look at this one. @RonWalker22 — thanks for submitting the bug. The `.gif` is super helpful. It looks like Cursorless is pulling in the correct context here. The `selection` for the target within the `Delete.run` command has multiple lines(in my example, I'm trying to delete two lines).

```
targets.at(0).selection.selection.start
{_line: 7, _character: 0}
targets.at(0).selection.selection.end
{_line: 8, _character: 0}
```

I thought that it had something to do with the line below having no characters, but the gif below shows that that even with text, deleting 2 lines preserves the one where the cursor is currently. 

![output](https://user-images.githubusercontent.com/1354217/163578287-98662560-f425-4af8-acd3-09d5b03f6184.gif)

I need to think about what a good next step would be. This seems to be a delete specific problem, ie. if I were to lines between, I'd want to select only those lines and not any newline characters. However, if I were to want to delete, I think the fix is likely to extend the select to the line below.

I'm looking through the VSCode API to see if we should be using a special API for delete vs. update.

**Comment by AndreasArvidsson** [comment]
The problem in essence with this is that the delete/chuck command depends on leading and trailing delimiter ranges. These ranges contains the new lines, commas and so on that needs to be removed together with the target. The problem with the between modifier is that it completely discards both the start and end targets and we are now left with just a raw range in between that has no understanding of the new line delimiter that should be discarded.

**Comment by Will-Sommers** [comment]
@AndreasArvidsson — thanks a bunch for the context. I'm looking through the code and I think the piece you're referencing is here in the [`compound_targets.py`](https://github.com/cursorless-dev/cursorless/blob/main/cursorless-talon/src/compound_targets.py#L37-L65) file?

Specifically these lines:

```
def is_anchor_included(range_connective: str):
    return range_connective not in ["rangeExclusive", "rangeExcludingStart"]

def is_active_included(range_connective: str):
    return range_connective not in ["rangeExclusive", "rangeExcludingEnd"]
```

Here's a few questions:

- I think what I hear you saying as well is that the type of action should perhaps have some influence on how we handle a selection? 
- What do you think a prudent "first stab" at this might be?

**Comment by AndreasArvidsson** [comment]
That's the talon side of it but the issue is in the vscode extension. 
* Definitely the selection you want to remove is not the same that you want to for example copy or select. We already do this in different ways in the extension
* I think this one will solve itself when we have the new object oriented targets so I would not touch this one for now at all
