### ISSUE TITLE
Surrounding pair problem in error python code

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#712]
`def funk(words:list<str>):`
`take pair` in `<str>` doesn't work

**Comment by auscompgeek** [comment]
Isn't that invalid Python? `list[str]` would be a valid type hint.

**Comment by pokey** [comment]
Yes, but the idea behind surrounding pairs is that they should work no matter what

**Comment by pokey** [comment]
The problem here is that we have code that tries to discard `<` if it is being used as the less than operator, so you don't get trapped by things like `if (foo < bar)`.  We avoid doing this if the `<` token is an error node, but in this case tree-sitter actually doesn't treat this `<` as an error node; it doesn't decide there's an error until it sees the `>`
