### ISSUE TITLE
Within cell set selection fails non deterministically on ci

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#845]
Seems to happen only on windows

https://github.com/cursorless-dev/cursorless/runs/7238130016?check_suite_focus=true#step:6:2236

**Comment by AndreasArvidsson** [comment]
Now it started happening more on mac for some reason

https://github.com/cursorless-dev/cursorless/pull/851

**Comment by pokey** [comment]
Prob need to tweak a sleep

I had an idea for that. Maybe we should sleep more each time the test fails, rather than sleeping the same amount each time

We could have a special sleep function where you pass in the test name and the name of the sleep (each sleep will need a name). Then the sleep function will initially sleep 1/4 of the requested time and store that it has done that sleep once. Next time that test runs, if it failed, the sleep function will see it had slept once before and sleep half the requested time. Then whole time, etc. by the time it is 5th try it is sleeping 4x

WDYT?

**Comment by AndreasArvidsson** [comment]
Incrementally increase sleep time is probably a good idea.
