### ISSUE TITLE
`touch item sun` inside jsx selects whole tag instead of attribute

### ISSUE THREAD

**Issue by SimeonC** [cursorless-dev/cursorless#912]
Using this code `<Button data-testid="Action Button" data-variant="bare">`

![CleanShot 2022-08-15 at 11 53 09](https://user-images.githubusercontent.com/1085899/184569419-b7b5cad2-ed4a-4e48-8b03-d0da2bdf22e4.png)

Say `touch key air`
![CleanShot 2022-08-15 at 11 53 41](https://user-images.githubusercontent.com/1085899/184569483-76a4b444-c421-4e2b-a06a-72d13f489ec1.png)
Selects `data-testid` as expected.

Say `touch value air`
![CleanShot 2022-08-15 at 11 54 22](https://user-images.githubusercontent.com/1085899/184569540-219baddd-2dd6-46b3-8f4e-49d830804a8f.png)
Also works as expected

Say `touch item air`
![CleanShot 2022-08-15 at 11 55 10](https://user-images.githubusercontent.com/1085899/184569599-ec66700a-24b1-4c4f-8bf2-6b2a285a577f.png)
Selects the whole contents of the JSX not `data-testid="Action Button"`

**Comment by pokey** [comment]
You can use "attribute" for that, although I can see how you'd expect "item" to work there, given we support it for key-value pairs elsewhere. Hmm. @AndreasArvidsson WDYT?

**Comment by SimeonC** [comment]
Ahh, yes that works thanks. Didn't know about `attribute`

**Comment by AndreasArvidsson** [comment]
Yeah it would probably be good if item worked here

**Comment by auscompgeek** [comment]
I definitely didn't expect `item` to select everything between `<>`

**Comment by pokey** [comment]
Yeah agreed that's unintuitive. Fwiw the reason it does that is that "item" is just a text-based matcher that selects items in a comma-separated list surrounded by matching pairs. So in this case it saw the code as a single element list between angle brackets 😄

**Comment by auscompgeek** [comment]
I'm unable to verify that this is fixed with Cursorless v0.26.740 and Parse tree v0.26.4.

Using the following source:

https://github.com/cursorless-dev/cursorless/blob/34d128fe33880991043cbeeeb3f23c689a721314/packages/cursorless-org/src/pages/cheatsheet.tsx#L19

`highlight item` (I'm using the keyboard interface):

![highlight item](https://github.com/cursorless-dev/cursorless/assets/128854/5ccbd6f9-bae4-44e8-a7f3-93c8ade13b0f)

`highlight attribute` still works as expected:

![highlight attribute](https://github.com/cursorless-dev/cursorless/assets/128854/3c1861bb-00c3-4011-9b89-11f8e75f9fe0)
